#!/bin/sh -e

export GOPATH=$PWD
export GO111MODULE=auto
trap "go clean -modcache" EXIT INT

ln -s src/github.com/containerd/containerd srcdir

(
cd srcdir
export GOFLAGS="-trimpath -mod=readonly -modcacherw"

make VERSION="v$2"
make DESTDIR="$1/usr" install
)

install -Dm755 run "$1/etc/sv/containerd/run"
install -Dm755 run "$1/etc/sysmgr/containerd"
ln -s /run/runit/supervise.containerd "$1/etc/sv/containerd/supervise"
